# Basic Site Settings
title: "Antonio Santoro"
description: "Portfolio personale: elettronica, stampa 3D e progetti interdisciplinari"
url: "https://antonio-santoro.github.io" # il tuo sito
baseurl: "" # lascia vuoto
locale: "en-US"
repository: "antonio-santoro.github.io"

# Theme
theme: jekyll-theme-cayman

# Author info
author:
  name: "Antonio Santoro"
  avatar: "profile.png" # opzionale, se vuoi la tua foto
  email: "antos3104@gmail.com"
  location: "Messina, Italia"
  bio: "Studente di Ingegneria Elettronica e appassionato di stampa 3D, modellazione e progetti interdisciplinari."
  github: "Antonio-Santoro"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Collections
collections:
  portfolio:
    output: true
    permalink: /portfolio/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single

# Markdown
markdown: kramdown
